name: llm-pipeline
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.11
  - pip
  # Core dependencies
  - fastapi>=0.68.1
  - uvicorn>=0.15.0
  - pydantic>=1.8.2
  - pandas>=2.0.0
  - numpy>=2.0.0
  - httpx>=0.23.0
  - pytz>=2021.1
  # ML dependencies
  - pytorch>=2.2.0
  - transformers>=4.40.2
  - tokenizers>=0.19.1
  - scikit-learn>=1.6.1
  # Development tools
  - black>=24.2.0
  - pylint>=3.0.3
  - pytest>=8.0.0
  - pytest-cov>=4.1.0
  - jupyter>=1.0.0
  - notebook>=7.0.7
  - ipykernel>=6.29.0
  # Use pip for packages not available in conda
  - pip:
    - apscheduler>=3.8.1
    - minio>=7.1.0
    - gunicorn>=21.2.0
    - python-json-logger>=2.0.7
    - sentry-sdk>=1.39.1
    - prometheus-client>=0.19.0 