global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - api_url: 'https://hooks.slack.com/services/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'
    channel: '#vm-performance'
    send_resolved: true
    icon_emoji: ':warning:'
    title: 'Alert: {{ .CommonLabels.alertname }}'
    text: "{{ range .Alerts }}*Alert:* {{ .Annotations.summary }}\n*Description:* {{ .Annotations.description }}\n{{ end }}"