---
- name: Scale up VirtualBox VM
  hosts: virtualbox_host
  connection: local
  gather_facts: false

  vars:
    vm_name: "{{ vm_name }}"
    new_ram_mb: "{{ new_ram_mb }}"
    new_cpu_count: "{{ new_cpu_count }}"

  tasks:
    - name: Get VM info
      command: VBoxManage showvminfo "{{ vm_name }}" --machinereadable
      register: vminfo

    - name: Check if VM is running
      set_fact:
        vm_running: "{{ 'VMState=\"running\"' in vminfo.stdout_lines }}"

    - name: Power off VM if running
      command: VBoxManage controlvm "{{ vm_name }}" poweroff
      when: vm_running

    - name: Wait for VM to fully power off
      command: VBoxManage showvminfo "{{ vm_name }}" --machinereadable
      register: waitinfo
      until: "'VMState=\"poweroff\"' in waitinfo.stdout"
      retries: 10
      delay: 1

    - name: Set new memory size
      command: VBoxManage modifyvm "{{ vm_name }}" --memory "{{ new_ram_mb }}"

    - name: Set new CPU count
      command: VBoxManage modifyvm "{{ vm_name }}" --cpus "{{ new_cpu_count }}"

    - name: Start the VM
      command: VBoxManage startvm "{{ vm_name }}" --type headless
